### PR TITLE
Hot fix ddpg

### PR DESCRIPTION
**Pull request by ymd-h**
This PR will improve #69 

I added base classes for Network and only Actor/Critic at DDPG were migrated.
Other networks will be migrated in future.

### CODE REVIEW

**Comment by keiohta** [comment]
Thank you for your PR!

Most codes look fine to me, except that some codes do not follow PEP8 coding style (missing blank in function arguments).

I'm considering whether to merge the network building codes, because it might sacrifice readability, so please give me some time to merge this.

**Comment by janbolle** [comment]
> I'm considering whether to merge the network building codes, because it might sacrifice readability, so please give me some time to merge this.

I would appreciate this, found this in code too and wanted to change this on my own..

**Comment by keiohta** [comment]
@ymd-h 
Sorry for delay. I am going to fix the corresponding codes **on new branch**, because the current master is too different from this PR. This is my responsibility, and I am deeply sorry.

As I wrote in the previous comment, I would deal with the following three problems out of four features as:

1. Specify mutable object (list) as default argument
2. Make a 0-deviated rondom noise
3. Don't call on_episode_end.

For the third one, might it cause some errors when we call `replay_buffer.on_episode_end()` every time even if the buffer type is not N-step related one? In your PR, it seems you call `replay_buffer.on_episode_end()` regardless of the buffer type, but you say it is problem in issue #69 as:
```
cpprb requires calling on_episode_end at the end of episode. Precisely speaking, it is not necessary as long as you don't use Nstep feature, but your Trainer is universal, it is a bug.
```

Please let me know if I have some misunderstanding.

**Comment by ymd-h** [comment]
Regardless of buffer type, we should call `on_episode_end()` at the end of episode. This is current design.

Since `Trainer` can be used with any buffers, we should call `on_episode_end()`, even though some type of buffers do nothing. (If you don't call, it is potentially bug.)

**Comment by keiohta** [comment]
Thanks, as I wrote in previous comment, I fixed the issue #69 on other branch referred to your commits.

**Pull request closed without merging**
