### PR TITLE
Docker Container Support

### PR DESCRIPTION
**Pull request by ymd-h**
This PR adds Dockerfiles to build container images for tf2rl (#110)

Two containers are pushed to GitHub Container Registry
- CPU only
- with Nvidia GPU

You need to create personal access token and set it as "GHCR_TOKEN"

### CODE REVIEW

**Comment by ymd-h** [comment]
I added documentation at README.md

**Comment by ymd-h** [comment]
Additionally, I realized the PR installed tf2rl from PyPI instead of local source.
It was fixed.

**Comment by keiohta** [comment]
Thanks for the PR! I created the PAT named "GHCR_TOKEN", and think the commits should work well.
However, I would like to test before merging this PR. So, can I ask how to test this?

**Comment by ymd-h** [comment]
Hi, @keiohta 

For testing container, you can build container at your local machine.

```bash
DOCKER_BUILDKIT=1 docker build -f Dockerfile -t tf2rl:cpu .
```

After that, you can run `tf2rl:cpu`.

For GPU container, please use Dockerfile.nvidia


For testing Actions, push as other branch with some test tag.

**Comment by keiohta** [comment]
I'm actually new to docker, so can you tell me what command do I exactly need to run the installed docker?
I tried `docker run tf2rl:cpu`, but it immediately finished.

**Comment by ymd-h** [comment]
The options you need are interactive session `-i` and tty `-t`. You can specify both with `-it`.


Additionally, If you want to mount local directory, please use `-v /local/dir:/mount/dir`.

**Comment by keiohta** [comment]
Thanks, it looks fine and I merge it.

**Pull request merged**
